apiVersion: v1
kind: Secret
metadata:
  name: ms-utilisateur-secret
  labels:
    app: ms-utilisateur
type: Opaque
stringData:
  # JWT Secret (should be a strong random key in production)
  JWT_SECRET: "mySecretKey123456789mySecretKey123456789mySecretKey123456789"

  # MySQL Password (already in ConfigMap but better in Secret)
  MYSQL_PASSWORD: "password"
  SPRING_DATASOURCE_PASSWORD: "password"

