apiVersion: v1
kind: Service
metadata:
  name: ms-utilisateur
  labels:
    app: ms-utilisateur
spec:
  type: NodePort
  selector:
    app: ms-utilisateur
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http

